WINDOW_WIDTH = 1028
WINDOW_HEIGHT = 500
BLOCK_SIZE = 20

TILE_SIZE = 50

FIRST_TREE = "./assets/tiles/tree.png"
HOUSE_TILE = "./FirstMap/img/housetile.png"

TILE_LAYER = 0
OBJ_LAYER = 3
PLAYER_LAYER = 2
